# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=120)),
                ('picture', models.ImageField(upload_to='files/pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[(b'running', b'Running'), (b'available', b'Available'), (b'outofservice', b'Out of Service')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('made', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.VehicleMaker')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taxiadmin.Person')),
                ('related_documents', models.ManyToManyField(to='core.Documents')),
            ],
            bases=('taxiadmin.person',),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='made',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.VehicleMaker'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.VehicleModel'),
        ),
    ]
