# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-26 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person')),
                ('related_documents', models.ManyToManyField(to='core.Documents')),
            ],
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=10)),
                ('year', models.CharField(blank=True, max_length=8, null=True)),
                ('vin', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[(b'ongoing', b'On Going'), (b'available', b'Available'), (b'outofservice', b'Out of Service')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('made', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.VehicleMaker')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='made',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.VehicleMaker'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.VehicleModel'),
        ),
    ]
