# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-05 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person')),
                ('rating', models.FloatField(default=0, help_text='Rating del conductor')),
                ('related_documents', models.ManyToManyField(help_text='Documentos asociados al conductor', to='core.Documents')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person')),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
            },
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.CharField(help_text='Placa del Vehiculo', max_length=30)),
                ('number', models.CharField(help_text='Numero de taxi', max_length=10)),
                ('year', models.CharField(blank=True, help_text='A\xf1o del Vehiculo', max_length=8, null=True)),
                ('vin', models.CharField(blank=True, help_text='Numero de Vin (Puede ser encontrado en la boleta de revision)', max_length=30, null=True)),
                ('color', models.CharField(blank=True, help_text='Color', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Veh\xedculo',
                'verbose_name_plural': 'Veh\xedculos',
            },
        ),
        migrations.CreateModel(
            name='VehicleMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo de la marca (Ej: Toyota)', max_length=100)),
            ],
            options={
                'verbose_name': 'Marca de Veh\xedculo',
                'verbose_name_plural': 'Marcas de Veh\xedculos',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo del modelo (Ej: Corolla)', max_length=100)),
                ('made', models.ForeignKey(help_text='Marca del Vehiculo', on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.VehicleMaker')),
            ],
            options={
                'verbose_name': 'Modelo de Veh\xedculo',
                'verbose_name_plural': 'Modelos de Veh\xedculos',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='made',
            field=models.ForeignKey(help_text='Marca del Vehiculo', on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.VehicleMaker'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(help_text='Modelo del Vehiculo', on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.VehicleModel'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(blank=True, default=None, help_text='El vehiculo asignado al conductor', null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.Vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set([('register',)]),
        ),
    ]
