# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-10 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='reviews',
            field=models.FloatField(default=0, help_text='Reviews que ha recibido el conductor', verbose_name='Reviews'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=0, help_text='Rating del conductor', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='related_documents',
            field=models.ManyToManyField(help_text='Documentos asociados al conductor', to='core.Documents', verbose_name='Documentos'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(blank=True, default=None, help_text='El vehículo asignado al conductor', null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.Vehicle', verbose_name='Vehículo'),
        ),
    ]
