# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-11 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiadmin', '0002_vehicleassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ongoing', 'On Going'), ('available', 'Available'), ('outofservice', 'Out of Service')], max_length=100),
        ),
    ]
