# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-12 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taxiadmin', '0003_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='RegisterDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
