# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-24 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiadmin', '0004_auto_20190217_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
