# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiadmin', '0004_purchase_registerdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='PaddedCardNo',
            field=models.IntegerField(max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ReferenceNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ShipToCountry',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ShipToEmail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ShipToFirstName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ShipToLastName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
