# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-24 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiadmin', '0005_driver_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=0, help_text='Rating del conductor'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='related_documents',
            field=models.ManyToManyField(help_text='Documentos asociados al conductor', to='core.Documents'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(blank=True, default=None, help_text='El vehiculo asignado al conductor', null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.Vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, help_text='Color', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='made',
            field=models.ForeignKey(help_text='Marca del Vehiculo', on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.VehicleMaker'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(help_text='Modelo del Vehiculo', on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.VehicleModel'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number',
            field=models.CharField(help_text='Numero de taxi', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='register',
            field=models.CharField(help_text='Placa del Vehiculo', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, help_text='Numero de Vin (Puede ser encontrado en la boleta de revision)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(blank=True, help_text='Año del Vehiculo', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaker',
            name='title',
            field=models.CharField(help_text='Titulo de la marca (Ej: Toyota)', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='made',
            field=models.ForeignKey(help_text='Marca del Vehiculo', on_delete=django.db.models.deletion.CASCADE, to='taxiadmin.VehicleMaker'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='title',
            field=models.CharField(help_text='Titulo del modelo (Ej: Corolla)', max_length=100),
        ),
    ]
