# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-18 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiadmin', '0005_auto_20210118_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='PaddedCardNo',
            field=models.IntegerField(blank=True, max_length=19, null=True),
        ),
    ]
