# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-12 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxiadmin', '0007_auto_20190226_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'Pasajero', 'verbose_name_plural': 'Pasajeros'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemaker',
            options={'verbose_name': 'Marca de Vehículo', 'verbose_name_plural': 'Marcas de Vehículos'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'verbose_name': 'Modelo de Vehículo', 'verbose_name_plural': 'Modelos de Vehículos'},
        ),
    ]
