# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='files/documents')),
                ('type', models.CharField(choices=[(b'licence', b"Driver's Licence"), (b'crs', b'Criminal Record Sheet')], max_length=1)),
            ],
        ),
    ]
