# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-10 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identifier',
            field=models.CharField(default='', help_text='Número de Identidad', max_length=30, unique=True, verbose_name='Número de Identidad'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(default='', help_text='Número de teléfono', max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(upload_to='files/pictures', verbose_name='Archivo de Imágen'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(default='', help_text='Usuario para accesar desde el app', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
