# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-26 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='identifier',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
