# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[(b'licence', b"Driver's Licence"), (b'crs', b'Criminal Record Sheet')], max_length=100),
        ),
    ]
