# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-02 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190226_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(default='', help_text='Numero de telefono', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('identifier', 'phone')]),
        ),
    ]
