# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-12 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190302_1237'),
        ('core', '0004_auto_20190225_1806'),
    ]

    operations = [
    ]
